sudo: required
dist: bionic
language: java
jdk:
  - oraclejdk11
python:
  - "3.6"
services: docker
before_install:
  - sudo apt-get update
  - ./gradlew clean build
script: 
  - docker-compose build


notifications:
  email: false