language: bash
services: docker
script: docker-compose build
before-deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
  deploy:
    provider: script
    script:
      docker push jardelpalagi/rest-spring-boot;
    on:
      branch: master

notifications:
  email: false