sudo: required
dist: bionic
language: java
jdk:
  - oraclejdk11
python:
  - "3.6"
services: docker
before_install:
  - sudo apt-get update
  - ./gradlew clean build
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
script:
  - docker-compose build
deploy:
  provider: script
  script:
    docker tag rest-spring-boot:latest jardelpalagi/rest-spring-boot:$TRAVIS_JOB_ID;
    docker push jardelpalagi/rest-spring-boot:$TRAVIS_JOB_ID;
  on:
    branch: master
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - eval (aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 880149143655.dkr.ecr.us-east-2.amazonaws.com)
  - docker tag rest-spring-boot:latest $IMG_REPO_URL:$TRAVIS_JOB_ID
  - docker push rest-spring-boot:latest $IMG_REPO_URL:$TRAVIS_JOB_ID
  - add-apt-repository ppa:eugenesan/ppa
  - apt-get update
  - apt-get install jq -y
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMG_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION -t 240

notifications:
  email: false