version: '3.4'
services:

  rest-spring-boot:
    image: jardelpalagi/rest-spring-boot
    restart: always
    build: ./
#    working_dir: /RestSpringBoot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
#    volumes:
#      - ./:/RestSpringBoot
#      - ~/.m2:/.m2
    ports:
      - "8080:8080"
#    command: ./gradlew build

